apm install atom-php-navigation
apm install docblockr
apm install fonts
apm install go-to-line
apm install language-vcl
apm install merge-conflicts
apm install minimap
apm install oceanic-next
apm install php-integrator-autocomplete-plus
apm install php-integrator-base
apm install php-integrator-call-tips
apm install php-integrator-linter
apm install php-integrator-navigation
apm install php-integrator-tooltips
apm install project-manager
apm install rubiks-syntax
apm install seti-syntax
apm install seti-ui
