#!/bin/bash

# Auto-installer for project sync to iCloud
# This script sets up automatic syncing of non-git directories from ~/proj to ~/Documents/Backup/proj

set -e

echo "=== Project Sync to iCloud - Auto Installer ==="
echo ""

# Check if running on macOS
if [[ "$OSTYPE" != "darwin"* ]]; then
    echo "❌ Error: This script only works on macOS."
    exit 1
fi

# Check if rsync is available
if ! command -v rsync &> /dev/null; then
    echo "❌ Error: rsync is not installed. Please install it first."
    exit 1
fi

# Check rsync version and warn if it's the old macOS version
RSYNC_VERSION=$(rsync --version | head -n1)
echo "Detected rsync: $RSYNC_VERSION"

# Check for terminal-notifier and suggest installation
if ! command -v terminal-notifier &> /dev/null; then
    echo ""
    echo "💡 Tip: Install terminal-notifier for better desktop notifications:"
    echo "   brew install terminal-notifier"
    echo "   (Without it, notifications will use dialog popups instead)"
fi

echo ""

# Get the current username
CURRENT_USER=$(whoami)
HOME_DIR="$HOME"

# Define paths
SOURCE_DIR="$HOME_DIR/proj"
DEST_DIR="$HOME_DIR/Documents/Backup/proj"
LOG_DIR="$HOME_DIR/.local/log"
LOG_FILE="$LOG_DIR/projsync.log"
ERROR_LOG="$LOG_DIR/projsync.error"
SCRIPT_DIR="$HOME_DIR/scripts"
SYNC_SCRIPT="$SCRIPT_DIR/sync-proj.sh"
PLIST_PATH="$HOME_DIR/Library/LaunchAgents/com.user.projsync.plist"

# Check if already installed (check for any of the key files)
ALREADY_INSTALLED=false
IS_RUNNING=false

if [ -f "$SYNC_SCRIPT" ] || [ -f "$PLIST_PATH" ]; then
    ALREADY_INSTALLED=true
fi

if launchctl list 2>/dev/null | grep -q "com.user.projsync"; then
    IS_RUNNING=true
fi

if [ "$ALREADY_INSTALLED" = true ]; then
    if [ "$IS_RUNNING" = true ]; then
        echo "⚠️  Project sync is already installed and running."
    else
        echo "⚠️  Project sync is already installed but not running."
    fi
    echo ""
    echo "Current installation:"
    [ -f "$SYNC_SCRIPT" ] && echo "  ✓ Sync script: $SYNC_SCRIPT"
    [ -f "$PLIST_PATH" ] && echo "  ✓ Config: $PLIST_PATH"
    echo ""
    read -p "Do you want to reinstall/update? This will replace existing files. (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Installation cancelled."
        echo ""
        echo "To manually sync: $SYNC_SCRIPT"
        echo "To start service: launchctl load $PLIST_PATH"
        echo "To stop service: launchctl unload $PLIST_PATH"
        exit 0
    fi

    # Unload existing job before reinstalling (if it's running)
    if [ "$IS_RUNNING" = true ]; then
        echo "Unloading existing sync job..."
        launchctl unload "$PLIST_PATH" 2>/dev/null || true
        echo "✓ Unloaded existing job"
    fi
fi

# Show installation plan
echo "=== Installation Plan ==="

# Check if source directory exists
if [ ! -d "$SOURCE_DIR" ]; then
    echo "⚠️  Warning: $SOURCE_DIR does not exist."
    read -p "Do you want to create it? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        mkdir -p "$SOURCE_DIR"
        echo "✓ Created $SOURCE_DIR"
    else
        echo "❌ Installation cancelled."
        exit 1
    fi
fi

# Check if Documents folder exists (should always exist on macOS, but let's be safe)
if [ ! -d "$HOME_DIR/Documents" ]; then
    echo "❌ Error: Documents folder not found. This is unusual for macOS."
    exit 1
fi

# Create destination directory in iCloud
echo "Creating destination directory..."
mkdir -p "$DEST_DIR"
echo "✓ Created $DEST_DIR"

# Create log directory (persistent, survives reboots)
mkdir -p "$LOG_DIR"
echo "✓ Created log directory $LOG_DIR"

# Create scripts directory if it doesn't exist
mkdir -p "$SCRIPT_DIR"
echo "✓ Created $SCRIPT_DIR"

# Create the sync script
echo "Creating sync script..."
cat > "$SYNC_SCRIPT" << SYNCSCRIPT
#!/bin/bash

####  this file is auto-generated by proj_sync_installer.sh ####
####  do not edit directly! edit proj_sync_installer.sh instead! ####

SOURCE_DIR="\$HOME/proj"
DEST_DIR="\$HOME/Documents/Backup/proj"
LOG_FILE="\$HOME/.local/log/projsync.log"

# Create destination if it doesn't exist
mkdir -p "\$DEST_DIR"

echo "Starting sync from \$SOURCE_DIR to \$DEST_DIR"
echo ""

# Rotate log if larger than 5MB
if [ -f "\$LOG_FILE" ] && [ "\$(wc -c < "\$LOG_FILE")" -gt 5242880 ]; then
    mv "\$LOG_FILE" "\$LOG_FILE.bak"
    echo "Log rotated at \$(date)" > "\$LOG_FILE"
fi

# Sync all files directly in ~/proj (not in subdirectories)
echo "Syncing root-level files..."
rsync -a --stats --exclude='*/' "\$SOURCE_DIR/" "\$DEST_DIR/"

echo ""
echo "Processing directories..."

# Now handle directories
for dir in "\$SOURCE_DIR"/*/; do
    # Skip if not a directory
    [ -d "\$dir" ] || continue

    dirname=\$(basename "\$dir")

    # Check if directory contains a .git folder
    if [ ! -d "\$dir/.git" ]; then
        # Not git-managed, sync it
        echo "Syncing directory: \$dirname"
        rsync -a --stats --delete "\$dir" "\$DEST_DIR/\$dirname/"
    else
        echo "Skipping git-managed directory: \$dirname"

        # Check if backup exists but is not yet marked as git-managed
        if [ -d "\$DEST_DIR/\$dirname" ] && [ ! -d "\$DEST_DIR/\$dirname (became git managed)" ]; then
            echo "⚠️  NOTICE: Directory '\$dirname' has become git-managed!"
            echo "   Renaming backup: \$dirname -> \$dirname (became git managed)"
            mv "\$DEST_DIR/\$dirname" "\$DEST_DIR/\$dirname (became git managed)"
            echo "   Please review '\$DEST_DIR/\$dirname (became git managed)' and decide if you want to keep or delete it."
            echo ""

            # Send notification (try terminal-notifier first, fallback to osascript dialog)
            NOTIF_TITLE="Project Sync - Git Repository Detected"
            NOTIF_MSG="Directory '\$dirname' became git-managed. Backup renamed to '\$dirname (became git managed)'. Please review in \$DEST_DIR/"

            if command -v terminal-notifier &> /dev/null; then
                terminal-notifier -title "\$NOTIF_TITLE" -message "\$NOTIF_MSG" -sound default 2>/dev/null
            else
                osascript -e "display dialog \"\$NOTIF_MSG\" with title \"\$NOTIF_TITLE\" buttons {\"OK\"} default button 1" &
            fi
        fi
    fi
done

echo ""
echo "Sync completed at \$(date)"
SYNCSCRIPT

chmod +x "$SYNC_SCRIPT"
echo "✓ Created sync script at $SYNC_SCRIPT"

# Create the launchd plist (with persistent log paths)
echo "Creating launchd configuration..."
cat > "$PLIST_PATH" << PLISTFILE
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.user.projsync</string>
    <key>ProgramArguments</key>
    <array>
        <string>$SYNC_SCRIPT</string>
    </array>
    <key>StartInterval</key>
    <integer>3600</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$LOG_FILE</string>
    <key>StandardErrorPath</key>
    <string>$ERROR_LOG</string>
</dict>
</plist>
PLISTFILE

echo "✓ Created launchd plist at $PLIST_PATH"

# Load the launchd job
echo "Loading launchd job..."
if launchctl load "$PLIST_PATH" 2>/dev/null; then
    echo "✓ Loaded launchd job"
else
    echo "⚠️  Warning: Could not load launchd job automatically."
    echo "   You may need to log out and log back in for it to start."
fi

# Run initial sync
echo ""
echo "Running initial sync..."
if "$SYNC_SCRIPT"; then
    echo "✓ Initial sync completed successfully"
else
    echo "⚠️  Warning: Initial sync encountered some issues. Check the output above."
fi

echo ""
echo "=== Installation Complete! ==="
echo ""
echo "Setup summary:"
echo "  Source directory: $SOURCE_DIR"
echo "  Destination directory: $DEST_DIR"
echo "  Sync script: $SYNC_SCRIPT"
echo "  Sync interval: Every hour"
echo ""
echo "Logs are available at:"
echo "  $LOG_FILE"
echo "  $ERROR_LOG"
echo ""
echo "Useful commands:"
echo "  Manual sync:     $SYNC_SCRIPT"
echo "  Stop auto-sync:  launchctl unload $PLIST_PATH"
echo "  Start auto-sync: launchctl load $PLIST_PATH"
echo "  Check status:    launchctl list | grep projsync"
echo "  View logs:       tail -f $LOG_FILE"
echo ""
echo "✓ Your non-git projects will now sync to iCloud automatically!"
